### ISSUE TITLE
Als Open Hiring wil ik werkgevers kunnen aanmaken, zodat ik bedrijven kan helpen met hun accounts.

### ISSUE THREAD

**Issue by Mathijs-04** [Mathijs-04/TLE1-Backlog#1]
**Acceptatiecriteria**
- [x] Als Open Hiring wil ik een aparte afgeschermde pagina met invulveld om een bedrijfsaccount aan te maken voor een werkgever

**Defenition Of Done**
- [x] WCAG A-level
- [x] Geen bugs of errors
- [x] Comments in iedere functie
- [x] Engelse code, Nederlandse comments
- [x] Mobile and Desktop interface
- [x] Getest in Chrome, Firefox and Safari
- [x] Voldoet aan de Style Guide
- [x] Volledige beveiliging volgens OWASP

**Comment by StefanMuijs** [comment]
leeg???
