### ISSUE TITLE
Als developer wil ik het inlog systeem van breeze omzetten naar de styling van de website zodat de user experience beter verloopt.

### ISSUE THREAD

**Issue by jaimyvdb03** [Mathijs-04/TLE1-Backlog#26]
**Acceptatiecriteria**
- [x] De inlog pagina volgt de style in de style guide
- [x] De register pagina volgt de style in de style guide
- [x] Mijn profiel pagina volgt de style in de style guide

**Defenition Of Done**
- [x] WCAG A-level
- [x] Geen bugs of errors
- [x] Engelse code, Nederlandse comments
- [x] Desktop interface
- [x] Voldoet aan de Style Guide
- [x] Volledige beveiliging volgens OWASP

**Comment by ItsMySquid** [comment]
Login.blade foutmelding?
Register Session status?
Nederlandse comments
